### PR TITLE
Remove non-shortest tests to clarify shortest functionality

### PR DESCRIPTION
**Pull request by khalatevarun**
Fix: https://github.com/anti-work/shortest/issues/122

Delete all the tests which are not in the "shortest" scope

Non-shortest test files:
Tests in lib, app, and other directories deal with broader functionalities (dashboard, config, etc.) and don’t directly belong to packages/shortest.

### CODE REVIEW

**Comment by m2rads** [comment]
Please also remove `vitest.config.ts` as well as vitest lib from `package.json`. Then run `pnpm install` to update the pnpm-lock.file. Thanks.

**Comment by khalatevarun** [comment]
> Please also remove `vitest.config.ts` as well as vitest lib from `package.json`. Then run `pnpm install` to update the pnpm-lock.file. Thanks.

done

**Review by m2rads — APPROVED** [review]

**Comment by m2rads** [comment]
Thank you. Looks good, you can merge it now.

**Comment by khalatevarun** [comment]
@m2rads I dont seem to have the merge rights to get this PR merged

**Comment by slavingia** [comment]
There's still page.test.ts?

**Comment by khalatevarun** [comment]
Missed it! Here's a fix PR to remove the same - https://github.com/anti-work/shortest/pull/131

**Pull request merged**
