### PR TITLE
Feat: API refinement and API validation support

### PR DESCRIPTION
**Pull request by m2rads**
Addresses Issue: https://github.com/anti-work/iffy/issues/225 

This PR ships v0.0.8 and completes migrating Iffy from playwright test to shortest.

### Added
- Added support for playwright's browser and playwright object model 
- Rename test namespace to shortest 
- Added new lifecycle method called .after() that will only run after the specific test case

- Updated shortest.yml

### CODE REVIEW

**Comment by slavingia** [comment]
Can you resolve this error? It's quite annoying

**Review by slavingia — APPROVED** [review]

**Comment by m2rads** [comment]
> Can you resolve this error? It's quite annoying

Sorry which error are you referring to?

**Comment by slavingia** [comment]
> @m2rads is attempting to deploy a commit to the Antiwork Team on [Vercel](https://vercel.com/).
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=Antiwork&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%2210772f97ade63bfa2954cf9f3da90562d5f479a1%22%7D%2C%22id%22%3A%22QmbNF6Xx86XGUx4xEai8GoB8gM5iCdqeX5Jb9mg36MrWa5%22%2C%22org%22%3A%22anti-work%22%2C%22prId%22%3A114%2C%22repo%22%3A%22shortest%22%7D).

**Comment by m2rads** [comment]
I think it's because I am working from a forked repo and we have Vercel protection turned on that checks for this. I will clone this repo from now on. 

image

**Pull request merged**
