### PR TITLE
feat: add mouse tracking feature in the browser

### PR DESCRIPTION
**Pull request by m2rads**
This feature addresses issue #118 in preparation for demo day

### Changes
- Added mouse tracking and click animations for better user experience

https://github.com/user-attachments/assets/53609112-c984-4c90-9912-a4ab367530c9

### CODE REVIEW

**Review by slavingia — APPROVED** [review]

**Comment by m2rads** [comment]
> Would be good to get build green

Yes, test are failing because of not being able to login. we need to add two more env vars to Github secrets such as: 
- CLERK_PUBLISHABLE_KEY
- CLERK_SECRET_KEY
- GITHUB_TOKEN

@slavingia If you could add these please would be great. Also if it's possible to be part of Antiwork org in Clerk would be great because then I can create a test account and use it in the workflow. Thanks in advance.

**Comment by m2rads** [comment]
Razvan asked for some more enhancements which I will make to this PR before merging. I will try to add issue #104 in this PR, if not I will open a new PR for that.

**Comment by m2rads** [comment]
Sure I will open a new one.

**Comment by m2rads** [comment]
@slavingia Seems like there is an issue with clerk authentication in preview env but the tests are passing locally. I will merge this branch for now to finish recording the demo. 

image

**Pull request merged**
