### PR TITLE
Feat: Making Playwright's page object available in Test Files

### PR DESCRIPTION
**Pull request by m2rads**
Mocking logging in is now possible: 

```typescript
await clerk.signIn({
        page,
        signInParams: { 
          strategy: "email_code", 
          identifier: "iffy+clerk_test@example.com" 
        },
 });
```

### CODE REVIEW

**Comment by m2rads** [comment]
API refinement is coming in the next PR.

**Comment by slavingia** [comment]
IMO should update shortest tests with each new feature so we can see it in use.

**Comment by m2rads** [comment]
So using page object is an optional parameter that can be used for mocking certain situations like login.

So for example in Iffy we would have this: 

```typescript
import { UITestBuilder } from '@antiwork/shortest';
import { clerk, clerkSetup } from "@clerk/testing/playwright";

define('Validate clerk authentication', async () => {
    beforeAll(async () => {
        await clerkSetup({
            frontendApiUrl: process.env.PLAYWRIGHT_TEST_BASE_URL ?? "http://localhost:3000",
        });
    });
  new UITestBuilder<any>('/')
    .before(async ({ page }) => {
      try {
        await page.goto("http://localhost:3000/dashboard", { 
          waitUntil: 'networkidle',
          timeout: 3000000
        });
        
        await clerk.signIn({
          page,
          signInParams: { 
            strategy: "email_code", 
            identifier: "iffy+clerk_test@example.com" 
          },
        });
      } catch (error) {
        console.error('Authentication error:', error);
      }
    })
    .test('Moderation text to be visible')
});
```

So this is now completely operational and we can finish onboarding Iffy but as we discussed it's messy. So the next PR I'm working on will make it a better UX and will send you the demo.

**Comment by m2rads** [comment]
Yes so with the new change we will have this:

```typescript
import {test} from '@antiwork/shortest'

test.before(async ({page}) => {
    try {
        await page.goto("http://localhost:3000/dashboard", { 
          waitUntil: 'networkidle',
          timeout: 3000000
        });
})
 test("user is redirected to /dashboard and the text Moderations is visible") 
```

**Comment by m2rads** [comment]
Sure so this change is coming in the next PR and it is not supported yet. So the example test are showing the current supported syntax. There are still some stuff that I am fixing. Once I have that read I will update all the test cases with the new syntax and open a PR.

**Comment by slavingia** [comment]
I think we should keep them in the same PR, as I don't have enough confidence those changes will indeed have the intended result until I see them.

**Comment by m2rads** [comment]
Ok then, let me close this for now and I will reopen with all the changes we discussed.

**Pull request closed without merging**
