### PR TITLE
Feature: Documentation page

### PR DESCRIPTION
**Pull request by m2rads**
Adding documentation site for shortest. (In progress...)

preview:
https://shortest-7tcj8fo3j-gumroad-dbdbd10c.vercel.app/docs/getting-started/introduction

New changes: 
- Added MDX based docs 
- Add support for dark mode
- Updated clerk lib and implementation 
- Removed nextjs experimental PPR support 
- Update react, react-dom, and nextjs library

### CODE REVIEW

**Comment by slavingia** [comment]
Breaking up into multiple PRs if not related would be good, that way higher chance of approval and less big things to revert if there's a bug

**Comment by m2rads** [comment]
Hi @slavingia I am working on the documentation site for shortest and I wanted to share it with you so far. Before I go more into details and finish things up please let me know what you think.

**Comment by slavingia** [comment]
Also why do we need this if we have an open source github + readme and a marketing homepage?

**Comment by m2rads** [comment]
Oh honestly I just read this and went for it.  

image

**Comment by m2rads** [comment]
Yeah most of the stuff are covered in the readme maybe we can hold on to this for later. I will cleanup the readme for now.

**Pull request closed without merging**
